[deployment]
deploymentTarget = "autoscale"
build = ["npm", "run", "build"]
run = ["npm", "run", "start"]
ignorePorts = false

[[deployment.domains]]
domain = "app.backstageos.com"

[[deployment.domains]]
domain = "beta.backstageos.com"

[env]
NODE_ENV = "production"